### DISCUSSION TITLE
device type weight

### DISCUSSION THREAD

**Discussion by r000m5** [netbox-community/devicetype-library#1096] [Q&A] [answered]
Hello,

Did anyone succeed in importing a devicetype in netbox including weight ? 
I don't understand what I did wrong  : for example weight is not imported with this device and netbox 3.4.4

```
---
manufacturer: Arista
model: CCS-720XP-24Y6
slug: ccs-720xp-24y6
part_number: CCS-720XP-24Y6
u_height: 1
is_full_depth: false
weight:
 - value: 8.55
   unit: kg
console-ports:
  - name: Console
    type: rj-45
power-ports:
  - name: PS1
    type: iec-60320-c14
    maximum_draw: 177
    allocated_draw: 164
  - name: PS2
    type: iec-60320-c14
    maximum_draw: 177
    allocated_draw: 164
interfaces:
  - name: Ethernet1
    type: 1000base-t
  - name: Ethernet2
    type: 1000base-t
  - name: Ethernet3
    type: 1000base-t
  - name: Ethernet4
    type: 1000base-t
  - name: Ethernet5
    type: 1000base-t
  - name: Ethernet6
    type: 1000base-t
  - name: Ethernet7
    type: 1000base-t
  - name: Ethernet8
    type: 1000base-t
  - name: Ethernet9
    type: 1000base-t
  - name: Ethernet10
    type: 1000base-t
  - name: Ethernet11
    type: 1000base-t
  - name: Ethernet12
    type: 1000base-t
  - name: Ethernet13
    type: 1000base-t
  - name: Ethernet14
    type: 1000base-t
  - name: Ethernet15
    type: 1000base-t
  - name: Ethernet16
    type: 1000base-t
  - name: Ethernet17
    type: 1000base-t
  - name: Ethernet18
    type: 1000base-t
  - name: Ethernet19
    type: 1000base-t
  - name: Ethernet20
    type: 1000base-t
  - name: Ethernet21
    type: 1000base-t
  - name: Ethernet22
    type: 1000base-t
  - name: Ethernet23
    type: 1000base-t
  - name: Ethernet24
    type: 1000base-t
  - name: Ethernet25
    type: 25gbase-x-sfp28
  - name: Ethernet26
    type: 25gbase-x-sfp28
  - name: Ethernet27
    type: 25gbase-x-sfp28
  - name: Ethernet28
    type: 25gbase-x-sfp28
  - name: Ethernet29
    type: 25gbase-x-sfp28
  - name: Ethernet30
    type: 25gbase-x-sfp28
  - name: Management1
    type: 1000base-t
    mgmt_only: true

```
