### DISCUSSION TITLE
Update device type with yaml

### DISCUSSION THREAD

**Discussion by BobZteD** [netbox-community/devicetype-library#1346] [Q&A]
Hi
I want to update device type with yaml, i've already add many device types that most of them already added as devices in racks, but some part of device type most be edited, like i/o module bays name..., i tried to update device types with same yaml that i used to import devices with some updated parts include device type "id" of that device, for example

```
---
manufacturer: Dell
model: VNX-5800-DPE
slug: vnx-5800-dpe
u_height: 3
is_full_depth: true

module-bays:
  - name: A-I/O-1
    position: A1
  - name: B-I/O-1
    position: B1
```
and this:

```
---
manufacturer: Dell
model: VNX-5800-DPE
slug: vnx-5800-dpe
u_height: 3
is_full_depth: true
id:120

module-bays:
  - name: A-I/O-0
    position: A0
  - name: B-I/O-0
    position: B0
```
but it will shows an error " Record 1: Device type with this Manufacturer and Model already exists."
is it possible at all or did i missed something? 
thanks
