### DISCUSSION TITLE
importing YAML-defined device type with images

### DISCUSSION THREAD

**Discussion by xavbroadcast** [netbox-community/devicetype-library#2326] [Q&A] [answered]
I was hoping I'd understood a cool feature but I can't get it to work so maybe I've misunderstood.

In the community device-library, the [documentation](https://github.com/netbox-community/devicetype-library/tree/master) suggests it's possible to define front and rear images by setting the boolean `front_image` and `rear_image` to `true`. By default, I understand the filename to be `<VALUE_IN_SLUG>.front.<acceptable_format>` and `<VALUE_IN_SLUG>.rear.<acceptable_format>`. My images are in PNG format and appear fine if manually uploaded via the web interface.

I've defined such a device-type (I took an original yaml file and edited it to make a few changes):
```
manufacturer: Fortinet
model: FortiGate 401F
slug: fortinet-fg-401f
description: Fortinet Firewall
default_platform: null
part_number: FG-401F
u_height: 1.0
is_full_depth: true
front_image: True
rear_image: true
subdevice_role: ''
airflow: front-to-rear
weight: 6.5
weight_unit: kg
comments: ''
console-ports:
- name: Console
  type: rj-45
  label: ''
  description: ''
- name: USB
  type: usb-a
  label: ''
  description: ''
power-ports:
- name: PSU 1
  type: iec-60320-c14
  maximum_draw: 197
  allocated_draw: 81
  label: ''
  description: ''
- name: PSU 2
  type: iec-60320-c14
  maximum_draw: 197
  allocated_draw: 81
  label: ''
  description: ''
interfaces:
- name: HA
  type: 1000base-t
  enabled: true
  mgmt_only: false
  label: ''
  description: Reserved for High Availability
  bridge: null
  poe_mode: ''
  poe_type: ''
  rf_role: ''
- name: MGMT
  type: 1000base-t
  enabled: true
  mgmt_only: true
  label: ''
  description: ''
  bridge: null
  poe_mode: ''
  poe_type: ''
  rf_role: ''
--8<---
```

Separately, I've uploaded the png files to the default location: `/opt/netbox/netbox/media/devicetype-images/`
```
/opt/netbox/netbox/media/devicetype-images$ ls -al
total 336
drwxrwxr-x 2 netbox root    4096 Sep  1 11:45 .
drwxrwxr-x 4 netbox root    4096 Aug 29 14:47 ..
-rw-r--r-- 1 netbox netbox 52783 Sep  1 09:58 fortinet-fg-401f.front.png
-rw-r--r-- 1 netbox netbox 89788 Sep  1 09:58 fortinet-fg-401f.rear.png
-rw-rw-r-- 1 netbox root      14 Aug 29 14:47 .gitignore
-rw-r--r-- 1 netbox netbox 88673 Sep  1 10:04 synology-rs4021xs.front.png
-rw-r--r-- 1 netbox netbox 95202 Sep  1 10:04 synology-rs4021xs.rear.png
```

What I was hoping was that when I imported the device type YAML file, the link would automatically be made to the PNG images corresponding to the device type slug text, but this doesn't appear to work, the links are not created:

![image](https://github.com/user-attachments/assets/3cd63fe9-8879-445c-8aed-4e40318f0060)

However, I also noticed that if using a CSV import, the `front_image` and `rear_image` fields are not present. I thought this might be because a CSV import is just that and there's no means to attach the image files at the same time, but maybe it's because the auto-linking between the media files located in the devicetype-images directory and the YAML file indicating they should be there no longer works?
