### ISSUE TITLE
suggestion to make tests for name not be typed

### ISSUE THREAD

**Issue by syyna** [netbox-community/devicetype-library#229]
Some devices literally have integers for their names.  Raritans for example have their power outlets be named 1,2,3 etc instead of Outlet1, Outlet2.  Currently, if I submit the template as 

```
power-outlets:
  - name: 1
    type: iec-60320-c13
    power_port: Inlet1
    feed_leg: A
```

It will fail.  Instead I have to submit as:

```
power-outlets:
  - name: Outlet1
    type: iec-60320-c13
    power_port: Inlet1
    feed_leg: A
```

This means its giong to be double work to change it back to what it is.  Netbox by itself is fine accepting only integers as names, but the devicetype-library isn't.

Thanks.
