### ISSUE TITLE
Add functionality for recording Rack Types for netbox 4.1.0+

### ISSUE THREAD

**Issue by justin-davisibm** [netbox-community/devicetype-library#2618]
I suppose this is more of a discussion on formatting as any logic would likely live in https://github.com/netbox-community/Device-Type-Library-Import, but I'd like to propose the following:

- Add new top level folder `rack-types`
- Children folders will follow the same `{{ manufacturer_name }}` format as device-types and module-types does today.
- Add new schema that supports the allowed field options for rack types in Netbox:
  - manufacturer (required)
  - model (required)
  - slug (required)
  - width (required)
  - u_height (required)
  - form_factor (2-post-frame, 4-post-frame, 4-post-cabinet, wall-frame, wall-frame-vertical, wall-cabinet, wall-cabinet-vertical)
  - starting_unit
  - desc_units (boolean)
  - outer_width
  - outer_depth
  - outer_unit (mm, in)
  - mounting_depth
  - weight
  - max_weight
  - weight_unit (kg, g, lb, oz)
  - description
  - comments
  - tags
  - id

This will allow a feature request to Device-Type-Library-Import to support Rack types as an importable object.

**Comment by BCurrell** [comment]
If this gets approved / added, I have access to the following 2 rack types I'd be willing to add files for:
- [Startech 42U 4-post open frame](https://www.startech.com/en-gb/server-management/4postrack42)
- [Startech 12U 2-post desktop](https://www.startech.com/en-gb/server-management/rk12od)

**Comment by phillf** [comment]
@harryajc, is this possible in current state devicetype-library or is this something that has to come down from upstream netbox?

**Comment by danner26** [comment]
Hey all, could you submit an example file built out for this? Attach it here and I will review. This might work well and if so we would be happy to help build it out/review what you build out

**Comment by BCurrell** [comment]
Example / actual file for Startech 42U 4 poster:

```yaml
---
manufacturer: Startech
model: 4 Post 42U
slug: startech-4postrack42
width: 19
u_height: 42
form_factor: 4-post-frame
description: Startech 4 Post 42U 19in rack with optional casters
starting_unut: 1
outer_width: 600
outer_unit: mm
# Adjustable depth, do we want the minimum or maximum depth?
# Minimum adjusted depth
mounting_depth: 560
# Maximum adjusted depth
# mounting_depth: 1017
weight: 38.5
# Different weights between stationary and on casters, which one?
# Stationary
# max_weight: 600
# Rolling
max_weight: 360
weight_unit: kg
```

Couple of possible options for `mounting_depth` and `max_weight`, not sure which option would be best. And I'm not sure I need to add a manufacturer somewhere, or if it handles that automatically?
