### ISSUE TITLE
Add: HPE FlexFabric 5945 48SFP28 8QSFP28

### ISSUE THREAD

**Issue by KmdKeen** [netbox-community/devicetype-library#2907]
This was missing in your library, so I did this: 

```
---
manufacturer: HPE
model: FlexFabric 5945 48SFP28 8QSFP28
slug: hpe-flexfabric-5945-48sfp28-8qsfp28
part_number: JQ074A
u_height: 1
is_full_depth: false
front_image: true
comments: '[HPE FlexFabric 5945 48SFP28 8QSFP28 Specs](https://www.hpe.com/psnow/doc/a00047323enw)'
weight: 15
weight_unit: kg
console-ports:
  - name: Console
    type: rj-45
  - name: USB Console
    type: usb-mini-b
  - name: USB
    type: usb-b
interfaces:
  - name: M-GigabitEthernet0/0/0
    type: 1000base-t
    mgmt_only: true
  - name: M-GigabitEthernet0/0/1
    type: 1000base-t
    mgmt_only: true
  - name: Twenty-FiveGigE1/0/1
    type: 25gbase-x-sfp28
  - name: Twenty-FiveGigE1/0/2
    type: 25gbase-x-sfp28
  - name: Twenty-FiveGigE1/0/3
    type: 25gbase-x-sfp28
  - name: Twenty-FiveGigE1/0/4
    type: 25gbase-x-sfp28
  - name: Twenty-FiveGigE1/0/5
    type: 25gbase-x-sfp28
  - name: Twenty-FiveGigE1/0/6
    type: 25gbase-x-sfp28
  - name: Twenty-FiveGigE1/0/7
    type: 25gbase-x-sfp28
  - name: Twenty-FiveGigE1/0/8
    type: 25gbase-x-sfp28
  - name: Twenty-FiveGigE1/0/9
    type: 25gbase-x-sfp28
  - name: Twenty-FiveGigE1/0/10
    type: 25gbase-x-sfp28
  - name: Twenty-FiveGigE1/0/11
    type: 25gbase-x-sfp28
  - name: Twenty-FiveGigE1/0/12
    type: 25gbase-x-sfp28
  - name: Twenty-FiveGigE1/0/13
    type: 25gbase-x-sfp28
  - name: Twenty-FiveGigE1/0/14
    type: 25gbase-x-sfp28
  - name: Twenty-FiveGigE1/0/15
    type: 25gbase-x-sfp28
  - name: Twenty-FiveGigE1/0/16
    type: 25gbase-x-sfp28
  - name: Twenty-FiveGigE1/0/17
    type: 25gbase-x-sfp28
  - name: Twenty-FiveGigE1/0/18
    type: 25gbase-x-sfp28
  - name: Twenty-FiveGigE1/0/19
    type: 25gbase-x-sfp28
  - name: Twenty-FiveGigE1/0/20
    type: 25gbase-x-sfp28
  - name: Twenty-FiveGigE1/0/21
    type: 25gbase-x-sfp28
  - name: Twenty-FiveGigE1/0/22
    type: 25gbase-x-sfp28
  - name: Twenty-FiveGigE1/0/23
    type: 25gbase-x-sfp28
  - name: Twenty-FiveGigE1/0/24
    type: 25gbase-x-sfp28
  - name: HundredGigE1/0/25
    type: 100gbase-x-qsfp28
  - name: HundredGigE1/0/26
    type: 100gbase-x-qsfp28
  - name: HundredGigE1/0/27
    type: 100gbase-x-qsfp28
  - name: HundredGigE1/0/28
    type: 100gbase-x-qsfp28
  - name: HundredGigE1/0/29
    type: 100gbase-x-qsfp28
  - name: HundredGigE1/0/30
    type: 100gbase-x-qsfp28
  - name: HundredGigE1/0/31
    type: 100gbase-x-qsfp28
  - name: HundredGigE1/0/32
    type: 100gbase-x-qsfp28
  - name: Twenty-FiveGigE1/0/33
    type: 25gbase-x-sfp28
  - name: Twenty-FiveGigE1/0/34
    type: 25gbase-x-sfp28
  - name: Twenty-FiveGigE1/0/35
    type: 25gbase-x-sfp28
  - name: Twenty-FiveGigE1/0/36
    type: 25gbase-x-sfp28
  - name: Twenty-FiveGigE1/0/37
    type: 25gbase-x-sfp28
  - name: Twenty-FiveGigE1/0/38
    type: 25gbase-x-sfp28
  - name: Twenty-FiveGigE1/0/39
    type: 25gbase-x-sfp28
  - name: Twenty-FiveGigE1/0/40
    type: 25gbase-x-sfp28
  - name: Twenty-FiveGigE1/0/41
    type: 25gbase-x-sfp28
  - name: Twenty-FiveGigE1/0/42
    type: 25gbase-x-sfp28
  - name: Twenty-FiveGigE1/0/43
    type: 25gbase-x-sfp28
  - name: Twenty-FiveGigE1/0/44
    type: 25gbase-x-sfp28
  - name: Twenty-FiveGigE1/0/45
    type: 25gbase-x-sfp28
  - name: Twenty-FiveGigE1/0/46
    type: 25gbase-x-sfp28
  - name: Twenty-FiveGigE1/0/47
    type: 25gbase-x-sfp28
  - name: Twenty-FiveGigE1/0/48
    type: 25gbase-x-sfp28
  - name: Twenty-FiveGigE1/0/49
    type: 25gbase-x-sfp28
  - name: Twenty-FiveGigE1/0/50
    type: 25gbase-x-sfp28
  - name: Twenty-FiveGigE1/0/51
    type: 25gbase-x-sfp28
  - name: Twenty-FiveGigE1/0/52
    type: 25gbase-x-sfp28
  - name: Twenty-FiveGigE1/0/53
    type: 25gbase-x-sfp28
  - name: Twenty-FiveGigE1/0/54
    type: 25gbase-x-sfp28
  - name: Twenty-FiveGigE1/0/55
    type: 25gbase-x-sfp28
  - name: Twenty-FiveGigE1/0/56
    type: 25gbase-x-sfp28
module-bays:
  - name: PWR1
    position: '1'
  - name: PWR2
    position: '2'
  - name: Fan1
    position: '1'
  - name: Fan2
    position: '2'
```

Maybe this helps someone out there.

Regards!
