### ISSUE TITLE
Cisco ASR9912 and a9922 Module Bay Update

### ISSUE THREAD

**Issue by segachan** [netbox-community/devicetype-library#2939]
Same as the title.

**Comment by segachan** [comment]
@harryajc 
I'm making device-type yaml, but I'm confusing how the relation and describing of the power module and power tray.

From ref.[2]:
> The chassis has four power trays. The version 2 power system has four AC or DC power modules in each power tray. The version 3 power system has three AC power modules or four DC power modules in each power tray.


- Cisco ASR 9922 chassis has the such as Power-bays in my guess. 
- A Power-tray can be housed in a Power-Bay, and Chassis could have multi Power-Trays. 
- Multi Power Modules could be housed in a Power Tray.

I feel it's difficult to represent the above Power Trays and Power modules, using `power-ports` in device-type yaml.

[1]https://www.cisco.com/c/en/us/products/collateral/routers/asr-9000-series-aggregation-services-routers/data_sheet_c78-501767.html

[2]https://www.cisco.com/c/en/us/td/docs/iosxr/asr9000/hardware-install/overview-reference/b-asr9k-overview-reference-guide/b-asr9k-overview-reference-guide_chapter_01.html

**Comment by harryajc** [comment]
Hi @segachan 
The correct way for this to be modeled, is the added them as `module-bays` on the device. Then create the required AC and DC PSUs as a module. Then in netbox you can install the required module into the module-bays and it will give you the power ports in that exist on those modules

**Comment by segachan** [comment]
Hi @harryajc Thank you for your reply.


> Hi [@segachan](https://github.com/segachan) The correct way for this to be modeled, is the added them as `module-bays` on the device. Then create the required AC and DC PSUs as a module. Then in netbox you can install the required module into the module-bays and it will give you the power ports in that exist on those modules


I'm trying to use `module-bays` feature.
Power Tray's number should be placeholed, and the Power Module's number should be also placeholded.
And Power Module is inserted to Power tray, and Power Tray is inserted to Chassis.

- Cisco ASR9922 Chassis
  - Power Tray **0**
    - Power Module 0 : PT**0**/M**0**
    - Power Module 1 : PT**0**/M**1**
    - Power Module 2 : PT**0**/M**2**
    - Power Module 3 : PT**0**/M**3**
  - Power Tray **1**
    - Power Module 0 : PT**1**/M**0**
    - Power Module 1 : PT**1**/M**1**
    - Power Module 2 : PT**1**/M**2**
    - Power Module 3 : PT**1**/M**3**
  - Power Tray 2...

https://netboxlabs.com/docs/netbox/en/stable/release-notes/version-4.1/
It seems that `Nested Device Modules` is supported.

How can I model two levels of nested relationships using placeholders?

I'm trying to mode the 9922 yaml and Power Tray yaml, Power Entry Module yaml, like below:
First, the snippet of modeled yaml for 9922:
```
module-bays:
  - name: 0/PT{module}
    label: 0/PT0
    position: 0
    description: Power Module Slot
```

Second, I'm trying to model the Power Tray `A9K-AC-PEM-V3` like below:
```
---
manufacturer: Cisco
model: A9K-AC-PEM-V3
slug: A9K-AC-PEM-V3
part_number: A9K-AC-PEM-V3
module-bays:
  - name: 0/PT{module}
    label: 0/PT
    position: 0
```

Third, I'm trying to model the Power Module `PWR-6KW-AC-V3` like below:
```
---
manufacturer: Cisco
model: PWR-6KW-AC-V3
part_number: PWR-6KW-AC-V3
comments: 6000W AC Power for ASR-9922
power-ports:
  - name: PS-{module}
    type: iec-60320-c20
    maximum_draw: 6000
```

refs.
![Image](https://github.com/user-attachments/assets/15bb53ec-9d65-40ef-ba4a-34a51126c9be)

https://www.cisco.com/c/en/us/td/docs/iosxr/asr9000/hardware-install/overview-reference/b-asr9k-overview-reference-guide/b-asr9k-overview-reference-guide_chapter_01.html

https://www.cisco.com/c/dam/en/us/td/i/300001-400000/340001-350000/344001-345000/344085.eps/_jcr_content/renditions/344085.jpg
