### ISSUE TITLE
Add Cisco Devices

### ISSUE THREAD

**Issue by TheRealBecks** [netbox-community/devicetype-library#362]
We use the Cisco Catalyst 2960S-48TD-L in our network. The information about the device can be found here: https://www.cisco.com/c/en/us/products/collateral/switches/catalyst-2960-s-series-switches/data_sheet_c78-726680.html
```
---
manufacturer: Cisco
model: Catalyst 2960S-48TD-L
slug: ws-c2960s-48td-l
part_number: WS-C2960S-48TD-L
is_full_depth: false
u_height: 1
interfaces:
  - name: FastEthernet0
    type: 100base-tx
    mgmt_only: true
  - name: GigabitEthernet1/0/1
    type: 1000base-t
  - name: GigabitEthernet1/0/2
    type: 1000base-t
  - name: GigabitEthernet1/0/3
    type: 1000base-t
  - name: GigabitEthernet1/0/4
    type: 1000base-t
  - name: GigabitEthernet1/0/5
    type: 1000base-t
  - name: GigabitEthernet1/0/6
    type: 1000base-t
  - name: GigabitEthernet1/0/7
    type: 1000base-t
  - name: GigabitEthernet1/0/8
    type: 1000base-t
  - name: GigabitEthernet1/0/9
    type: 1000base-t
  - name: GigabitEthernet1/0/10
    type: 1000base-t
  - name: GigabitEthernet1/0/11
    type: 1000base-t
  - name: GigabitEthernet1/0/12
    type: 1000base-t
  - name: GigabitEthernet1/0/13
    type: 1000base-t
  - name: GigabitEthernet1/0/14
    type: 1000base-t
  - name: GigabitEthernet1/0/15
    type: 1000base-t
  - name: GigabitEthernet1/0/16
    type: 1000base-t
  - name: GigabitEthernet1/0/17
    type: 1000base-t
  - name: GigabitEthernet1/0/18
    type: 1000base-t
  - name: GigabitEthernet1/0/19
    type: 1000base-t
  - name: GigabitEthernet1/0/20
    type: 1000base-t
  - name: GigabitEthernet1/0/21
    type: 1000base-t
  - name: GigabitEthernet1/0/22
    type: 1000base-t
  - name: GigabitEthernet1/0/23
    type: 1000base-t
  - name: GigabitEthernet1/0/24
    type: 1000base-t
  - name: GigabitEthernet1/0/25
    type: 1000base-t
  - name: GigabitEthernet1/0/26
    type: 1000base-t
  - name: GigabitEthernet1/0/27
    type: 1000base-t
  - name: GigabitEthernet1/0/28
    type: 1000base-t
  - name: GigabitEthernet1/0/29
    type: 1000base-t
  - name: GigabitEthernet1/0/30
    type: 1000base-t
  - name: GigabitEthernet1/0/31
    type: 1000base-t
  - name: GigabitEthernet1/0/32
    type: 1000base-t
  - name: GigabitEthernet1/0/33
    type: 1000base-t
  - name: GigabitEthernet1/0/34
    type: 1000base-t
  - name: GigabitEthernet1/0/35
    type: 1000base-t
  - name: GigabitEthernet1/0/36
    type: 1000base-t
  - name: GigabitEthernet1/0/37
    type: 1000base-t
  - name: GigabitEthernet1/0/38
    type: 1000base-t
  - name: GigabitEthernet1/0/39
    type: 1000base-t
  - name: GigabitEthernet1/0/40
    type: 1000base-t
  - name: GigabitEthernet1/0/41
    type: 1000base-t
  - name: GigabitEthernet1/0/42
    type: 1000base-t
  - name: GigabitEthernet1/0/43
    type: 1000base-t
  - name: GigabitEthernet1/0/44
    type: 1000base-t
  - name: GigabitEthernet1/0/45
    type: 1000base-t
  - name: GigabitEthernet1/0/46
    type: 1000base-t
  - name: GigabitEthernet1/0/47
    type: 1000base-t
  - name: GigabitEthernet1/0/48
    type: 1000base-t
  - name: GigabitEthernet1/0/49
    type: 1000base-x-sfp
  - name: GigabitEthernet1/0/50
    type: 1000base-x-sfp
  - name: TenGigabitEthernet1/0/1
    type: 10gbase-x-sfpp
  - name: TenGigabitEthernet1/0/2
    type: 10gbase-x-sfpp
console-ports:
  - name: con0
    type: rj-45
power-ports:
  - name: PSU0
    type: iec-60320-c14
    maximum_draw: 55
```

Please add the device to your library, thanks!
