### ISSUE TITLE
Can APC NMC modules be converted from devices to modules?

### ISSUE THREAD

**Issue by twilley** [netbox-community/devicetype-library#821]
APC NMC modules are currently modeled as devices. Their definitions can be found in the following files:
- device-types/APC/AP9617.yaml
- device-types/APC/AP9618.yaml
- device-types/APC/AP9619.yaml
- device-types/APC/AP9630.yaml
- device-types/APC/AP9631.yaml
- device-types/APC/AP9640.yaml
- device-types/APC/AP9641.yaml

The device definitions look good, but adding them to a UPS poses some challenges. 

- Both devices must be created, with unique names and all the other required fields, before the NMC can be installed into the UPS.
- UPSes and NMCs are currently two discrete devices and I think a device/module relationship would be more appropriate.

For example, Consider the following device/module models:

UPS device model:
```
---
manufacturer: APC
model: SMT1500RM2U
slug: smt1500rm2u
part_number: SMT1500RM2U
u_height: 2
is_full_depth: true
console-ports:
  - name: Serial
    type: rj-45
  - name: USB
    type: usb-b
power-ports:
  - name: Source
    type: nema-5-15p
power-outlets:
  - name: Group 1 Outlet 1
    type: nema-5-15r
  - name: Group 1 Outlet 2
    type: nema-5-15r
  - name: Group 1 Outlet 3
    type: nema-5-15r
  - name: Group 2 Outlet 1
    type: nema-5-15r
  - name: Group 2 Outlet 2
    type: nema-5-15r
  - name: Group 2 Outlet 3
    type: nema-5-15r
module-bays:
  - name: NMC Slot
```
NMC module model:
```
---
manufacturer: APC
model: AP9641
part_number: AP9641
u_height: 0
is_full_depth: false
comments: UPS Network Management Card 3 with Environmental Monitoring
subdevice_role: child
interfaces:
  - name: Network
    type: 1000base-t
    mgmt_only: true
```

The UPS is the device, and the NMC can be installed in the NMC Slot module-bay.

I can provide a pull request if this is a good idea.
